document.writeln("<div id=\'fixedMenu\' class=\'top\'>");
document.writeln("	<div class=\'top-bar\'>");
document.writeln("		<div class=\'container\'>");
document.writeln("			<p>SIE<span>国际暑期学校</span>International Summer Sessions</p>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<div class=\'top-box\'>");
document.writeln("		<div class=\'container\'>");
document.writeln("			<div class=\'logo-box pull-left\'>");
document.writeln("				<a href=\'../index.html\' target=\'_blank\'>");
document.writeln("					<img src=\'../../public/img/logo.png\' alt=\'sieSchool\' />");
document.writeln("				</a>");
document.writeln("			</div>");
document.writeln("			<div class=\'nav-box pull-right\'>");
document.writeln("				<div class=\'language text-right\'>");
document.writeln("					 <a href=\'../user/login.html\' title=\'登录\'>登录</a>");
document.writeln("					<a href=\'../user/register-step01.html\' title=\'注册\'>注册</a>");
document.writeln("					<a href=\'../user/user-center.html\' title=\'个人中心\' class='username' target=\'_blank\'>yannan.wang@sieschool.org</a>");
document.writeln("					<a href=\'javascript:;\' class='userout' title=\'退出登录\'>退出</a>");
document.writeln("					<a href=\'javascript:window.location.href=window.location.href.replace('/en','/cn')\' title=\'中文\'><img src=\'../../public/img/language-cn.png\' /></a>");
document.writeln("					<a href=\'javascript:window.location.href=window.location.href.replace('/cn','/en')\' title=\'English\'><img src=\'../../public/img/language-en.png\' /></a>");
document.writeln("				</div>");
document.writeln("				<div class=\'nav\'>");
document.writeln("					<ul>");
document.writeln("						<li class=\'dropdown active\'>");
document.writeln("						  	<a id=\'nav-01\' class=\'nav-link btn\' href=\'index.html\' role=\'button\'>首页</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'dropdown\'>");
document.writeln("						  	<a id=\'nav-01\' class=\'nav-link btn\' href=\'javascript:;\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>暑校介绍 <i class=\'fa fa-angle-down\'></i></a>");
document.writeln("						  	<ul class=\'dropdown-menu\' aria-labelledby=\'nav-01\'>");
document.writeln("						    	<li><a href=\'../about-us/about-sie\'>关于SIE</a></li>");
document.writeln("						    	<li><a href=\'../about-us/about-ecnu\'>关于ECNU</a></li>");
document.writeln("						    	<li><a href=\'../about-us/about-bnu\'>关于BJTU</a></li>");
document.writeln("						  	</ul>");
document.writeln("						</li>");
document.writeln("						<li class=\'dropdown\'>");
document.writeln("						  	<a id=\'nav-02\' class=\'nav-link btn\' href=\'javascript:;\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>暑校课程 <i class=\'fa fa-angle-down\'></i></a>");
document.writeln("						  	<ul class=\'dropdown-menu\' aria-labelledby=\'nav-03\'>");
document.writeln("						    	<li><a href=\'../courses/course-list\'>课程列表</a></li>");
document.writeln("						    	<li><a href=\'../faculty/current-faculty\'>现任教授</a></li>");
document.writeln("						    	<li><a href=\'../academics/add-drop\'>课程设置</a></li>");
document.writeln("						    	<li><a href=\'../academics/academic-calendar\'>暑校日程</a></li>");
document.writeln("						    	<li><a href=\'../courses/course-format\'>研究项目</a></li>");
document.writeln("						    	<li><a href=\'../faculty/former-faculty\'>往届教授</a></li>");
document.writeln("						  	</ul>");
document.writeln("						</li>");
document.writeln("						<li class=\'dropdown\'>");
document.writeln("						  	<a id=\'nav-03\' class=\'nav-link btn\' href=\'javascript:;\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>学费详情 <i class=\'fa fa-angle-down\'></i></a>");
document.writeln("						  	<ul class=\'dropdown-menu\' aria-labelledby=\'nav-02\'>");
document.writeln("						    	<li><a href=\'../application/tuition\'>学费价格</a></li>");
document.writeln("						    	<li><a href=\'../application/scholarship\'>奖学金</a></li>");
document.writeln("						    	<li><a href=\'../application/refund\'>退款事宜</a></li>");
document.writeln("						    	<li><a href=\'../application/paytype\'>支付方式</a></li>");
document.writeln("						  	</ul>");
document.writeln("						</li>");
document.writeln("						<li class=\'dropdown\'>");
document.writeln("						  	<a id=\'nav-04\' class=\'nav-link btn\' href=\'javascript:;\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>申请指南 <i class=\'fa fa-angle-down\'></i></a>");
document.writeln("						  	<ul class=\'dropdown-menu\' aria-labelledby=\'nav-04\'>");
document.writeln("						    	<li><a href=\'../application/how-to-apply\'>申请流程</a></li>");
document.writeln("						    	<li><a href=\'../academics/credit-transfer\'>转学分指南</a></li>");
document.writeln("						    	<li><a href=\'../academics/cdgdc-verification\'>CDGDC认证</a></li>");
document.writeln("						    	<li><a href=\'../academics/wes-verification\'>WES认证</a></li>");
document.writeln("						    	<li><a href=\'../academics/order-transcript\'>成绩单申请</a></li>");
document.writeln("						    	<li><a href=\'../academics/eligibility\'>申请要求</a></li>");
document.writeln("						  	</ul>");
document.writeln("						</li>");
document.writeln("						<li class=\'dropdown\'>");
document.writeln("						  	<a id=\'nav-05\' class=\'nav-link btn\' href=\'javascript:;\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>校园生活 <i class=\'fa fa-angle-down\'></i></a>");
document.writeln("						  	<ul class=\'dropdown-menu\' aria-labelledby=\'nav-06\'>");
document.writeln("						    	<li><a href=\'../campus-life/housing\'>校区住宿</a></li>");
document.writeln("						    	<li><a href=\'../campus-life/highlights\'>精彩瞬间</a></li>");
document.writeln("						  	</ul>");
document.writeln("						</li>");
document.writeln("						<li class=\'dropdown\'>");
document.writeln("						  	<a id=\'nav-06\' class=\'nav-link btn\' href=\'javascript:;\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>联系我们 <i class=\'fa fa-angle-down\'></i></a>");
document.writeln("						  	<ul class=\'dropdown-menu\' aria-labelledby=\'nav-07\'>");
document.writeln("						    	<li><a href=\'../contact-us/contact-us\'>联系我们</a></li>");
document.writeln("						    	<li><a href=\'../contact-us/faq\'>常见问题</a></li>");
document.writeln("						    	<li><a href=\'../contact-us/internship\'>实习招聘</a></li>");
document.writeln("						  	</ul>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</div>");