document.writeln("<!-- footer -->");
document.writeln("<div id=\'footer\'>");
document.writeln("	<div class=\'container text-light\'>");
document.writeln("		<ul class=\'row\'>");
document.writeln("			<li class=\'col-xs-3\'>");
document.writeln("				<div class=\'logo pull-right\'>");
document.writeln("					<img class=\'img-responsive\' src=\'../../public/img/logo.png\' alt=\'TRU国际暑期项目\' />");
document.writeln("				</div>");
document.writeln("			</li>");
document.writeln("			<li class=\'col-xs-3\'>");
document.writeln("				<div class=\'about\'>");
document.writeln("					<h2>关注我们</h2>");
document.writeln("					<p class=\'mt20\'>");
document.writeln("						<a href=\'#\'><i class=\'fa fa-facebook-official\'></i></a>");
document.writeln("						<a href=\'#\'><i class=\'fa fa-weibo\'></i></a>");
document.writeln("						<a href=\'#\'><i class=\'fa fa-twitter\'></i></a>");
document.writeln("						<a href=\'#\'><i class=\'fa fa-wechat\'></i></a>");
document.writeln("						<a href=\'#\'><i class=\'fa fa-qq\'></i></a>");
document.writeln("					</p>");
document.writeln("				</div>");
document.writeln("			</li>");
document.writeln("			<li class=\'col-xs-3\'>");
document.writeln("				<div class=\'contact\'>");
document.writeln("					<h2>联系我们</h2>");
document.writeln("					<p class=\'mt10\'>中国：010-69853211</p>");
document.writeln("					<p>加拿大：123456894</p>");
document.writeln("					<p>邮箱：support@TRU.org.cn</p>");
document.writeln("				</div>");
document.writeln("			</li>");
document.writeln("			<li class=\'col-xs-3\'>");
document.writeln("				<div class=\'wechat\'>");
document.writeln("					<div class=\'wechat-cont\'>");
document.writeln("						<img class=\'img-responsive\' src=\'../../public/img/wechat-consult.png\' alt=\'\' />");
document.writeln("						<p>微信咨询号</p>");
document.writeln("					</div>");
document.writeln("					<div class=\'wechat-cont\'>");
document.writeln("						<img class=\'img-responsive\' src=\'../../public/img/wechat-public.png\' alt=\'\' />");
document.writeln("						<p>微信公众号</p>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</li>");
document.writeln("		</ul>");
document.writeln("		<p class=\'copyright text-center\'>");
document.writeln("			<span>Copyright © 2009 Sinoway International Education Group Limited</span>");
document.writeln("			<span>京ICP证000007</span>");
document.writeln("		</p>");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<!-- float-ad -->");
document.writeln("<div class=\'float-ad\'>");
document.writeln("	<div class=\'ad-box\'>");
document.writeln("		<a href=\'javascript:;\'><i class=\'fa fa-qrcode\'></i></a>");
document.writeln("		<div class=\'ad-cont none\'>");
document.writeln("			<em></em>");
document.writeln("			<img class=\'img-responsive\' src=\'../../public/img/wechat-consult.png\' alt=\'\' />");
document.writeln("			<p>微信咨询号</p>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<div class=\'ad-box\'>");
document.writeln("		<a href=\'#top-a\' class=\'to-a-link\'><i class=\'fa fa-angle-up\'></i></a>");
document.writeln("	</div>");
document.writeln("</div>");