document.writeln("<div class=\'top\'>");
document.writeln("	<div class=\'container\'>");
document.writeln("		<div class=\'logo pull-left\'>");
document.writeln("			<a href=\'../index/index.html\' target=\'_blank\'>");
document.writeln("				<img class=\'img-responsive\' src=\'../../public/img/logo.png\' alt=\'TRU国际暑期项目\' />");
document.writeln("			</a>");
document.writeln("		</div>");
document.writeln("		<div class=\'nav pull-left\'>");
document.writeln("			<ul>");
document.writeln("				<li class=\'active\'>");
document.writeln("				  	<a class=\'nav-link btn\' href=\'../index/index.html\' role=\'button\'>暑校首页</a>");
document.writeln("				</li>");
document.writeln("				<li class=\'dropdown\'>");
document.writeln("				  	<a id=\'nav-01\' class=\'nav-link btn\' href=\'javascript:;\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>校区选择 <i class=\'fa fa-angle-down\'></i></a>");
document.writeln("				  	<ul class=\'dropdown-menu\' aria-labelledby=\'nav-01\'>");
document.writeln("				    	<li><a href=\'../campus/campus-ecnu.html\'>华东师范大学(ECNU)</a></li>");
document.writeln("				    	<li><a href=\'../campus/campus-bjtu.html\'>北京交通大学(BJTU)</a></li>");
document.writeln("				  	</ul>");
document.writeln("				</li>");
document.writeln("				<li class=\'dropdown\'>");
document.writeln("				  	<a id=\'nav-02\' class=\'nav-link btn\' href=\'javascript:;\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>课程列表 <i class=\'fa fa-angle-down\'></i></a>");
document.writeln("				  	<ul class=\'dropdown-menu\' aria-labelledby=\'nav-02\'>");
document.writeln("				    	<li><a href=\'../courses/courses.html\'>全部课程列表</a></li>");
document.writeln("				    	<li><a href=\'../courses/courses-ecnu.html\'>华东师范 (ECNU)课程列表</a></li>");
document.writeln("				    	<li><a href=\'../courses/courses-bjtu.html\'>北交大 (BJTU)课程列表</a></li>");
document.writeln("				  	</ul>");
document.writeln("				</li>");
document.writeln("				<li class=\'dropdown\'>");
document.writeln("				  	<a id=\'nav-03\' class=\'nav-link btn\' href=\'javascript:;\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>学术准则 <i class=\'fa fa-angle-down\'></i></a>");
document.writeln("				  	<ul class=\'dropdown-menu\' aria-labelledby=\'nav-03\'>");
document.writeln("				    	<li><a href=\'../academics/academics.html\'>学术政策</a></li>");
document.writeln("				    	<li><a href=\'../academics/grade.html\'>评分标准</a></li>");
document.writeln("				    	<li><a href=\'../academics/calendar.html\'>日程表</a></li>");
document.writeln("				    	<li><a href=\'../academics/report.html\'>成绩单</a></li>");
document.writeln("				    	<li><a href=\'../academics/credit.html\'>转学分流程</a></li>");
document.writeln("				  	</ul>");
document.writeln("				</li>");
document.writeln("				<li class=\'dropdown\'>");
document.writeln("				  	<a id=\'nav-04\' class=\'nav-link btn\' href=\'javascript:;\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>学费支付 <i class=\'fa fa-angle-down\'></i></a>");
document.writeln("				  	<ul class=\'dropdown-menu\' aria-labelledby=\'nav-04\'>");
document.writeln("				    	<li><a href=\'../tuition/price.html\'>学费价格</a></li>");
document.writeln("				    	<li><a href=\'../tuition/paymen.html\'>支付方式</a></li>");
document.writeln("				    	<li><a href=\'../tuition/refund.html\'>退款</a></li>");
document.writeln("				  	</ul>");
document.writeln("				</li>");
document.writeln("				<li class=\'\'>");
document.writeln("				  	<a class=\'nav-link btn\' href=\'../recruit/recruit.html\' role=\'button\'>诚聘英才</a>");
document.writeln("				</li>");
document.writeln("				<li class=\'\'>");
document.writeln("				  	<a class=\'nav-link btn\' href=\'../contact/contact.html\' role=\'button\'>联系我们</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("		<div class=\'pull-right\'>");
document.writeln("			<div class=\'login-box pull-left\'>");
document.writeln("				<div>");

document.writeln('				<a class="btn btn-warning-ghost" title="登录" id="login_modal_btn" data-toggle="modal" data-target="#modal-wechat">登录</a>');
document.writeln('               <a class="btn btn-reg" title="注册" data-toggle="modal" data-target="#modal-wechat">注册</a>    ' );
document.writeln("				</div>");
document.writeln("				<div class=\'dropdown\' style='display: none'>");
document.writeln("					<a id=\'user-head\' class=\'user-head\' href=\'javascript:;\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'></a>");
document.writeln("					<div class=\'user-head-box dropdown-menu\' aria-labelledby=\'user-head\'>");
document.writeln("						<em></em>");
document.writeln("						<p><a class=\'username\' href=\'../user/user-center.html\'>yannan.wang@sieschool.org</a></p>");
document.writeln("						<p class=\'mt10\'>");
document.writeln("							<a class=\'btn btn-xs userpsd\' data-toggle=\'modal\' data-target=\'#modal-psd\'>更改密码</a>");
document.writeln("							<a class=\'btn btn-xs btn-info userout\' href=\'javascript:;\'>退出</a>");
document.writeln("						</p>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			<div class=\'language pull-right\'>");
document.writeln("				<a href=\'../index/index.html\'>简体中文</a>");
document.writeln("				<a class=\'text-light\' href=\'../../en/index.html\'>English</a>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</div>");